### ISSUE TITLE
Chore: move to Botkit platform

### ISSUE THREAD

**Issue by viscoze** [datarockets/mona#22]
## Tension
When I use Mona I want to get new feature faster and not to see any vulnerabilities so I can use it with pleasure
 
## Solution
Move Mona to the Botkit platform

* [x] order water #24 
* [x] reply to a greeting #25 
* [x] reply to mentioning #35

**Comment by AleksSenkou** [comment]
I'd like to raise an issue *Which features we would like to move to botkit and how not to forget to move them all?* as a part of the chore.

The problem is in tests absence. We can't really run something to check that all required functionality is with us.

I can see **two ways as a workaround**:
1) The fastest - write a description including a list of current stable-working features and check that everything is added before the release
2) It's a 1. option plus prewritten tests for covering features on botkit.

Thoughts? // @datarockets/cuties @dzhlobo

**Comment by DDKatch** [comment]
There's a list of abilities for Mona to do:
1) order water
2) reply to greeting
3) reply to mentioning

**Comment by AleksSenkou** [comment]
FYI: updated chore with checklist of what's needed
